version: '3'
services:
    myits-portal-web:
        container_name: base-nextjs
        image: node:alpine
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        command: yarn dev
        environment:
            - VIRTUAL_HOST=${VIRTUAL_HOST}
            - VIRTUAL_PORT=${VIRTUAL_PORT}
            - SELF_SIGNED_HOST=${SELF_SIGNED_HOST}
        ports:
            - "3000:3000"
        dns:
            - 202.46.129.2
            - 202.46.129.3
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - nginx-proxy-network

networks:
    nginx-proxy-network:
        external: true